version: 2

jobs:
    build:
      machine: true
      steps:
        - checkout
        - run: wget -qO- get.nextflow.io | bash ; chmod 755 nextflow ; sudo mv ~/project/nextflow /usr/local/bin/ ; sudo apt-get install graphviz
        - run: cd ~ && git clone --depth=1 https://github.com/IARCbioinfo/data_test.git
        - run: echo " docker.runOptions = '-u $(id -u):$(id -g)' " > ~/.nextflow/config
        - run: cd ~/project/ ; docker build -t iarcbioinfo/svaba-nf .
        - run: cd ; nextflow run ~/project/svaba.nf --help
        - run: cd ; nextflow run ~/project/svaba.nf -with-docker iarcbioinfo/svaba-nf --input_folder ~/data_test/BAM/ --ref ~/data_test/REF/17.fasta --correspondance ~/data_test/correspondance.txt --options " --override-reference-check "
        - run: cd ; mv ~/nf-pipeline_info/svaba_dag.html ~/project/
        - deploy:
            branch: [dev, master]
            command: chmod +x deploy.sh && ./deploy.sh
